//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplikim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aplikim()
        {
            this.Rezervims = new HashSet<Rezervim>();
        }
    
        public int Id_Aplikim { get; set; }
        public Nullable<int> Pozc_Id { get; set; }
        public Nullable<int> Komp_Id { get; set; }
        public Nullable<System.DateTime> Orari { get; set; }
    
        public virtual Kompania Kompania { get; set; }
        public virtual PozicionPune PozicionPune { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervim> Rezervims { get; set; }
    }
}
