//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplikuesi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aplikuesi()
        {
            this.Rezervims = new HashSet<Rezervim>();
        }
    
        public int Perd_ID { get; set; }
        public string Emri { get; set; }
        public string Mbiemeri { get; set; }
        public int Nr_Kontakti { get; set; }
        public string Adresa { get; set; }
        public Nullable<int> Roli_ID { get; set; }
    
        public virtual ROLI ROLI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervim> Rezervims { get; set; }
    }
}
