//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kompania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kompania()
        {
            this.Aplikims = new HashSet<Aplikim>();
            this.PozicionPunes = new HashSet<PozicionPune>();
        }
    
        public int ID_Kompani { get; set; }
        public string Emri { get; set; }
        public Nullable<int> Tipi_ID { get; set; }
        public string Adresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aplikim> Aplikims { get; set; }
        public virtual Lloji Lloji { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozicionPune> PozicionPunes { get; set; }
    }
}
