//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozicionPune
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PozicionPune()
        {
            this.Aplikims = new HashSet<Aplikim>();
            this.Rezervims = new HashSet<Rezervim>();
        }
    
        public int Id_Pozicion { get; set; }
        public string Emri_Poz { get; set; }
        public string Tipi { get; set; }
        public Nullable<int> ID_Kompanie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aplikim> Aplikims { get; set; }
        public virtual Kompania Kompania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervim> Rezervims { get; set; }
    }
}
