//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervim
    {
        public int ID_Rezervim { get; set; }
        public Nullable<int> ID_Pozicion { get; set; }
        public Nullable<int> ID_Aplikimi { get; set; }
        public Nullable<bool> Anulluar { get; set; }
        public Nullable<int> ID_Perdorues { get; set; }
    
        public virtual Aplikim Aplikim { get; set; }
        public virtual Aplikuesi Aplikuesi { get; set; }
        public virtual PozicionPune PozicionPune { get; set; }
    }
}
